language: node_js

os:
  - linux

compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes --yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev

install:
  - npm install

node_js:
  - "4.2"
  - "0.12"
